
public class Run_Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		Test_Exception te = new Test _Exception();
		int [] a = {22,33,44,55,66,77};
		try {
		System.out.println(a[6]);
		} catch (Exception e) {
			System.out.print(e.getMessage());
		}
		
		
			
		}

	}

}
